name = "tspdt"
compatibility_date = "2023-12-06"
node_compat = true


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tspdt"
database_id = "cbf154c4-2b39-430d-aebf-e5bd8426775e"