import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CommandBar } from "@/components/command";
import { GlobalCommands } from "./global-commands";
import { R } from "./replicache";
import { BodyProvider } from "./body-provider";
import { ActionProvider } from "./action-provider";
import { FilterProvider } from "./filter-provider";
import { getPageSession } from "@/core/auth/validate";
import { UserProvider } from "./user-session";

const inter = Inter({ subsets: ["latin"] });

// export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  actions,
}: {
  children: React.ReactNode;
  actions: React.ReactNode;
}) {
  //   const session = await getPageSession();

  return (
    <html lang="en">
      {/* <UserProvider session={session}> */}
      {/* <R> */}
      <CommandBar>
        <BodyProvider>
          {/* <ActionProvider> */}
          <FilterProvider>
            <GlobalCommands>{children}</GlobalCommands>
          </FilterProvider>
          {/* </ActionProvider> */}
        </BodyProvider>
      </CommandBar>
      {/* </R> */}
      {/* </UserProvider> */}
    </html>
  );
}
