import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CommandBar } from "@/components/command";
import { GlobalCommands } from "./global-commands";
import { R } from "./replicache";

const inter = Inter({ subsets: ["latin"] });

// export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <R>
        <CommandBar>
          <body
            className={`${inter.className} bg-zinc-900 text-zinc-50 mx-auto flex flex-col gap-4 px-1`}
          >
            <GlobalCommands>
              <header className="flex justify-center w-full grow">
                <Link href="/">
                  <h1 className="text-2xl font-bold tracking-tight">
                    They Shoot Pictures, Don't They?
                  </h1>
                </Link>
              </header>
              <main className="mx-auto max-w-5xl">{children}</main>
            </GlobalCommands>
          </body>
        </CommandBar>
      </R>
    </html>
  );
}
