import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CommandBar } from "@/components/command";
import { GlobalCommands } from "./global-commands";
import { R } from "./replicache";
import { BodyProvider } from "./body-provider";

const inter = Inter({ subsets: ["latin"] });

// export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <R>
        <CommandBar>
          <BodyProvider>
            <GlobalCommands>
              <header className="flex w-full grow mx-auto items-center max-w-5xl h-24">
                <Link href="/">
                  <h1 className="text-2xl leading-tight text-white font-semibold tracking-tight drop-shadow-md">
                    TSPDT
                  </h1>
                </Link>
              </header>
              <main className="mx-auto max-w-5xl">{children}</main>
            </GlobalCommands>
          </BodyProvider>
        </CommandBar>
      </R>
    </html>
  );
}
