name: 'Backend Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Bun setup'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 'Bun install'
        run: bun install
      
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.15.0'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: packages/api
          command: deploy src/index.ts
          packageManager: bun
          secrets: |
            CI
        env:
          CI: true
          NO_D1_WARNING: true
