name: "Next.JS deployment"

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     paths:
#       - "apps/web/**"

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install

      - name: Build
        run: |
          cd apps/web
          export API_URL=${{ secrets.API_URL }}
          bunx @cloudflare/next-on-pages@1

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: tspdt
          directory: .vercel/output/static
          branch: main
          wranglerVersion: "3"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/web
